--
-- JBoss, Home of Professional Open Source
-- Copyright 2013, Red Hat, Inc. and/or its affiliates, and individual
-- contributors by the @authors tag. See the copyright.txt in the
-- distribution for a full listing of individual contributors.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- http://www.apache.org/licenses/LICENSE-2.0
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-- You can use this file to load seed data into the database using SQL statements
--insert into Registrant(id, name, email, phone_number) values (0, 'John Smith', 'john.smith@mailinator.com', '2125551212')
DROP TABLE USERROLES;
CREATE TABLE USERROLES(ROLE VARCHAR2(20) NOT NULL, USERNAME VARCHAR2(20) NOT NULL);

INSERT INTO userroles (role,username) VALUES ('TutorialUser','user');

INSERT INTO usuario (id,name,password) VALUES (1,'user','pwd');

commit;

Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('1','jessicabiel@diam.com','Jessica Biel','(59)23883-2266');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('2','louis_zamperini@ornare.com','Louis Zamperini','(41)91642-8654');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('3','terry_fox@dictumst.com','Terry Fox','(50)09714-4906');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('4','martinanavratilova@enim.com','Martina Navratilova','(59)23883-2266');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('5','samuell.jackson@dictumst.com','Samuel L. Jackson','(98)55901-7308');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('6','joe.dimaggio@augue.com','Joe DiMaggio','(89)26220-2687');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('7','philip_ii_of_macedon@neque.com','Philip II of Macedon','(26)96312-7566');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('8','marcus.aurelius@rhoncus.com','Marcus Aurelius','(55)63580-2087');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('9','benito.mussolini@in.com','Benito Mussolini','(25)44164-1222');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('10','karen.smyers@porttitor.com','Karen Smyers','(66)65146-2167');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('11','rogerfederer@integer.com','Roger Federer','(15)56898-6048');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('12','robert.carlyle@sed.com','Robert Carlyle','(55)78779-9981');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('13','chrisjohn@tincidunt.com','Chris John','(26)00536-5045');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('14','abrahamlincoln@enim.com','Abraham Lincoln','(91)60645-1600');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('15','ahmadshahmasoudnationalhero@nulla.com','Ahmad Shah Masoud National Hero','(68)84645-8240');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('16','georgewashington@in.com','George Washington','(33)44854-0102');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('17','samueleto@fermentum.com','Samuel Eto','(33)10499-1277');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('18','ian.thorpe@nulla.com','Ian Thorpe','(77)27639-9422');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('19','kubla.khan@at.com','Kubla Khan','(44)78382-9138');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('20','ericthered@ornare.com','Eric the Red','(24)95173-6625');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('21','atilla.the.hun@libero.com','atilla the hun','(27)97907-2249');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('22','sanath.jayasuriya@est.com','Sanath Jayasuriya','(37)77090-6598');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('23','alexanderkarelin@at.com','Alexander Karelin','(80)21575-1478');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('24','james.madison@turpis.com','James Madison','(92)57989-0525');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('25','jahangir.khan@tincidunt.com','Jahangir Khan','(35)40958-1792');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('26','imran_khan@bibendum.com','Imran Khan','(54)34557-9710');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('27','benjamin_franklin@at.com','Benjamin Franklin','(69)27252-1832');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('28','charles.de.gaulle@lectus.com','Charles de Gaulle','(20)49502-5824');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('29','heather.mckay@vel.com','Heather McKay','(25)75254-2797');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('30','xerxes.the.great@mollis.com','Xerxes the Great','(92)56992-6183');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('31','moctezuma_i@elit.com','Moctezuma I','(89)10101-2702');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('32','brielarson@mauris.com','Brie Larson','(69)34207-4935');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('33','peter_the_great@tristique.com','Peter the Great','(29)97626-4068');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('34','joan.of.arc@condimentum.com','Joan of Arc','(59)93002-6252');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('35','stevesmith@nunc.com','Steve Smith','(11)74993-5608');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('36','kirsten.dunst@senectus.com','Kirsten Dunst','(80)94775-3000');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('37','elizabethiofengland@eget.com','Elizabeth I of England','(60)25587-9732');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('39','steve.young@eu.com','Steve Young','(73)25149-4453');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('40','joseph.addai@lobortis.com','Joseph Addai','(45)50793-5944');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('41','alexanderthegreat@mi.com','Alexander The Great','(58)83631-3905');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('42','jason.statham@a.com','Jason Statham','(98)38743-4838');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('43','johnadams@felis.com','John Adams','(73)30631-8281');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('44','henry.rono@ac.com','Henry Rono','(77)38114-5921');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('45','wil.wheaton@dignissim.com','Wil Wheaton','(77)85144-4198');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('46','brian_odriscoll@quisque.com','Brian ODriscoll','(71)58246-0765');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('47','emmy_rossum@viverra.com','Emmy Rossum','(65)32852-1231');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('48','julius_peppers@est.com','Julius Peppers','(00)05905-4164');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('49','kellanlutz@curabitur.com','Kellan Lutz','(24)94717-1050');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('50','joseph.stalin@non.com','Joseph Stalin','(71)39051-4159');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('51','lakebell@at.com','Lake Bell','(81)68027-3073');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('52','andrew.garfield@sed.com','Andrew Garfield','(84)01822-3343');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('53','bradleycooper@etiam.com','Bradley Cooper','(93)42674-8118');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('54','bailee.madison@quam.com','Bailee Madison','(39)05874-1832');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('55','jenna_dewan-tatum@gravida.com','Jenna Dewan-Tatum','(76)17994-1515');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('56','margaretthatcher@mattis.com','Margaret Thatcher','(15)92902-1859');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('57','crazy.horse@consequat.com','Crazy Horse','(31)01333-2079');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('58','jessica.dube@massa.com','Jessica Dubé','(74)72787-4876');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('59','jeffersonperez@odio.com','Jefferson Perez','(93)60580-0714');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('60','david.rudisha@mattis.com','David Rudisha','(84)36270-3566');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('61','mustafa_kemal_ataturk@elit.com','Mustafa Kemal Atatürk','(07)65196-1805');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('62','sonny_bill_williams@duis.com','Sonny Bill Williams','(65)80826-4865');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('63','nikolajuriši?@amet.com','Nikola Juriši?','(83)85927-7722');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('64','georgest.pierre@semper.com','George St.Pierre','(94)27139-3615');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('65','sylvester_stallone@ultricies.com','Sylvester Stallone','(66)47731-3583');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('66','lennox_lewis@posuere.com','Lennox Lewis','(91)14597-1335');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('67','joseph_morgan@enim.com','Joseph Morgan','(76)54573-2851');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('68','alberto_contador@scelerisque.com','Alberto Contador','(40)53871-2520');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('69','frederickthegreat@ullamcorper.com','Frederick the Great','(05)33032-5227');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('70','candace_parker@viverra.com','Candace Parker','(36)97187-8444');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('71','mikhailgorbachev@est.com','Mikhail Gorbachev','(91)64284-6305');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('72','james.j..braddock@tincidunt.com','James J. Braddock','(55)40640-6039');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('73','sibel_kekilli@nisl.com','Sibel Kekilli','(19)96463-4814');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('74','rajon_rondo@phasellus.com','Rajon Rondo','(06)56935-2364');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('75','katherineheigl@elit.com','Katherine Heigl','(79)14249-6287');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('76','thomas.jefferson@aliquam.com','Thomas Jefferson','(95)35235-8718');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('77','johnny.depp@neque.com','Johnny Depp','(47)39396-6594');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('78','emperormeiji@at.com','Emperor Meiji','(27)23384-9367');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('79','niccolo.machiavelli@cras.com','Niccolò Machiavelli','(65)71352-2978');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('80','nelson_mandela@varius.com','Nelson Mandela','(95)40260-1401');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('81','sultanii.abdulhamidkhan@mi.com','Sultan II. Abdulhamid Khan','(22)29934-4475');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('83','cleopatra@vitae.com','Cleopatra','(28)43051-1705');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('84','ali_karimi@imperdiet.com','Ali Karimi','(79)65421-7678');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('85','abdel_latif_abu_haif@velit.com','Abdel Latif Abu Haif','(99)73977-7588');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('86','sachin.tendulkar@id.com','Sachin Tendulkar','(82)81112-2209');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('88','tiki.barber@et.com','Tiki Barber','(74)12042-0688');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('89','candiceaccola@condimentum.com','Candice Accola','(42)83956-6603');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('90','rick.mears@nisi.com','Rick Mears','(67)68666-4041');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('91','elizabeth_henstridge@massa.com','Elizabeth Henstridge','(41)67288-6811');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('92','liam.hemsworth@elit.com','Liam Hemsworth','(23)65978-9588');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('93','widukind@pretium.com','Widukind','(89)12184-5312');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('94','josip_broz_tito@aliquam.com','Josip Broz Tito','(95)43798-8590');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('95','kimraver@velit.com','Kim Raver','(69)85399-0105');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('96','andersonsilva@id.com','Anderson Silva','(54)97048-2625');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('97','natalieportman@nulla.com','Natalie Portman','(64)60602-2856');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('98','eden.sher@sit.com','Eden Sher','(42)76824-4882');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('99','alison_brie@mi.com','Alison Brie','(29)77985-0177');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('100','maradona@fringilla.com','Maradona','(03)16262-6741');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('101','karl_kirk@rutrum.com','Karl Kirk','(59)20610-8668');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('102','ute_upton@nec.com','Ute Upton','(53)93728-2424');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('103','tami.hodge@parturient.com','Tami Hodge','(04)10856-6812');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('104','cheree_thorpe@turpis.com','Cheree Thorpe','(03)85827-8683');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('105','charlettehaigh@sed.com','Charlette Haigh','(94)48067-5914');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('106','hellen.faulkner@dignissim.com','Hellen Faulkner','(34)09583-0839');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('107','luannarice@in.com','Luanna Rice','(88)38938-6159');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('108','evelina.rowland@bibendum.com','Evelina Rowland','(63)03291-0870');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('109','kris.horn@pharetra.com','Kris Horn','(74)05489-2789');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('110','cassidy.stevens@sed.com','Cassidy Stevens','(36)25632-5810');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('111','corie.burton@sed.com','Corie Burton','(76)10365-5442');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('112','marg_holden@ligula.com','Marg Holden','(45)27476-1324');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('113','kena.walker@tempor.com','Kena Walker','(22)52339-7856');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('114','rachal_nicholls@gravida.com','Rachal Nicholls','(33)67457-2210');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('115','moises_ferreira@turpis.com','Moises Ferreira','(45)50222-4817');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('116','jordan.bloom@faucibus.com','Jordan Bloom','(43)47917-5569');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('117','deloisekidd@ac.com','Deloise Kidd','(62)90995-3087');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('118','leonorahough@cum.com','Leonora Hough','(78)78163-1267');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('119','junita.holding@amet.com','Junita Holding','(93)47939-2813');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('120','johnson.gould@massa.com','Johnson Gould','(54)56097-0112');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('121','marilynbassett@et.com','Marilyn Bassett','(40)56764-3474');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('122','lemuel_mcneil@sed.com','Lemuel Mcneil','(88)16322-0856');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('123','beatamahoney@sed.com','Beata Mahoney','(46)62168-0940');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('124','thi_paterson@sem.com','Thi Paterson','(54)54264-1090');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('125','eryn.cotton@massa.com','Eryn Cotton','(21)85318-8282');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('126','katelin_munro@morbi.com','Katelin Munro','(31)30557-0499');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('127','samellaappleton@vulputate.com','Samella Appleton','(29)19693-1028');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('128','fonda_daniels@morbi.com','Fonda Daniels','(41)25650-9219');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('129','jolandacarroll@adipiscing.com','Jolanda Carroll','(13)07647-6112');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('130','syble.peterson@est.com','Syble Peterson','(65)98474-0399');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('131','corey.gregory@arcu.com','Corey Gregory','(67)19005-7196');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('132','raguel_amin@sollicitudin.com','Raguel Amin','(76)71297-7346');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('133','sachiko.dunlop@tincidunt.com','Sachiko Dunlop','(70)43054-2795');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('134','rusty_greaves@eget.com','Rusty Greaves','(85)33498-8273');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('135','jeanett.pearson@egestas.com','Jeanett Pearson','(14)58534-5338');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('136','jaysonbullock@velit.com','Jayson Bullock','(01)55439-4030');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('137','joshstone@duis.com','Josh Stone','(83)14061-4891');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('138','catrinaadams@porttitor.com','Catrina Adams','(27)42499-0369');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('139','johanne_best@donec.com','Johanne Best','(90)72867-6261');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('140','lainerawlings@ipsum.com','Laine Rawlings','(13)82723-6361');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('141','cyrus.meredith@tortor.com','Cyrus Meredith','(99)85145-2461');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('142','miyoko.page@non.com','Miyoko Page','(23)91443-5631');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('143','tamekia_mulligan@libero.com','Tamekia Mulligan','(09)36847-7765');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('144','brantaustin@vitae.com','Brant Austin','(12)73001-5144');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('145','eveliamccormick@sit.com','Evelia Mccormick','(37)20375-6581');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('146','shanekalang@rutrum.com','Shaneka Lang','(51)66463-8101');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('147','helen.welsh@velit.com','Helen Welsh','(78)38982-4156');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('148','sallie_wiggins@egestas.com','Sallie Wiggins','(82)98080-8348');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('149','columbus.matthams@ut.com','Columbus Matthams','(86)62772-4439');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('150','kimberlieast@at.com','Kimberli East','(23)84411-8248');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('151','mitsue_maguire@ullamcorper.com','Mitsue Maguire','(46)80914-3532');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('152','tressie_sampson@ante.com','Tressie Sampson','(18)05646-0824');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('153','debrah_mackay@lectus.com','Debrah Mackay','(34)46704-1260');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('154','sharleen.stamp@molestie.com','Sharleen Stamp','(86)52764-3455');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('155','taniasutton@at.com','Tania Sutton','(43)93737-0917');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('156','merrileepeel@nec.com','Merrilee Peel','(35)40775-6856');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('157','avelina.davie@dolor.com','Avelina Davie','(87)43314-1788');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('158','simonnepaul@sem.com','Simonne Paul','(46)33628-6071');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('159','zacheryparker@eu.com','Zachery Parker','(99)90424-7376');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('160','gwennhutchings@eget.com','Gwenn Hutchings','(62)27200-8069');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('161','matt_blundell@cursus.com','Matt Blundell','(82)95943-8182');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('162','christena.milne@euismod.com','Christena Milne','(64)41246-6792');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('163','hillarytimms@et.com','Hillary Timms','(23)53350-2728');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('164','tennille_walton@turpis.com','Tennille Walton','(64)19328-4567');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('165','danutaross@neque.com','Danuta Ross','(08)24187-3976');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('166','merrillsalter@turpis.com','Merrill Salter','(24)70023-1503');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('167','galina_morrison@malesuada.com','Galina Morrison','(44)56990-6052');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('168','thu_brook@enim.com','Thu Brook','(21)06319-8817');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('169','delinda.hurst@pretium.com','Delinda Hurst','(29)40536-4096');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('170','margit.dillon@elementum.com','Margit Dillon','(59)89554-0754');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('171','lashaunhodson@ornare.com','Lashaun Hodson','(11)60129-1982');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('172','devon_carter@enim.com','Devon Carter','(62)17782-2408');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('173','emil.bailey@neque.com','Emil Bailey','(90)28316-2547');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('174','elligough@diam.com','Elli Gough','(11)61368-2060');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('175','petermills@vitae.com','Peter Mills','(68)80316-4951');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('176','fredricka_barnard@ornare.com','Fredricka Barnard','(52)87943-4467');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('177','luigi_tucker@non.com','Luigi Tucker','(26)47303-0900');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('178','sarai_logan@neque.com','Sarai Logan','(54)02096-4946');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('179','stefania_o_neill@sit.com','Stefania O neill','(15)41715-8665');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('180','corliss_wilkes@turpis.com','Corliss Wilkes','(26)15513-2493');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('181','yolondaphillips@in.com','Yolonda Phillips','(25)48603-0580');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('182','florida.rossi@viverra.com','Florida Rossi','(66)82266-1637');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('183','marchelle_sargent@ullamcorper.com','Marchelle Sargent','(89)06617-7371');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('184','mai_cunningham@fusce.com','Mai Cunningham','(13)64446-6917');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('185','joeymarshall@mollis.com','Joey Marshall','(42)25661-2887');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('186','yelenabrowning@pharetra.com','Yelena Browning','(33)22923-8362');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('187','sparkle_power@at.com','Sparkle Power','(13)59221-5764');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('188','marquismolloy@risus.com','Marquis Molloy','(36)83500-2409');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('189','grantjarvis@non.com','Grant Jarvis','(28)89239-1064');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('190','karma_bates@mi.com','Karma Bates','(93)48657-4504');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('191','zona.gibbins@venenatis.com','Zona Gibbins','(55)42500-9677');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('192','ivette.smith@elementum.com','Ivette Smith','(23)64394-6798');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('193','julissa.tait@urna.com','Julissa Tait','(34)01369-3100');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('194','wesleyglover@adipiscing.com','Wesley Glover','(58)89194-4189');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('195','afton.may@dolor.com','Afton May','(60)11691-3569');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('196','james.neville@arcu.com','James Neville','(35)94322-0604');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('197','maud_lomas@id.com','Maud Lomas','(16)26418-9403');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('198','inge_sadler@facilisis.com','Inge Sadler','(45)25924-1243');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('199','else.dickinson@lacus.com','Else Dickinson','(75)64190-9286');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('200','pia.fernandez@pellentesque.com','Pia Fernandez','(22)83562-6143');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('201','kenethhowells@pulvinar.com','Keneth Howells','(57)72275-3664');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('202','lynda.frame@nisl.com','Lynda Frame','(31)32829-1124');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('203','spring.finney@feugiat.com','Spring Finney','(02)39979-5147');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('204','terresa_king@sem.com','Terresa King','(64)75258-7333');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('205','cordia.naylor@volutpat.com','Cordia Naylor','(10)72863-8492');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('206','saulhall@tincidunt.com','Saul Hall','(36)66542-0531');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('207','garry_o_brien@eget.com','Garry O brien','(91)15472-1823');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('208','stepanie_ryan@placerat.com','Stepanie Ryan','(52)56226-2708');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('209','rosena.sanders@sem.com','Rosena Sanders','(49)77190-1849');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('210','nanciedonald@viverra.com','Nancie Donald','(18)78754-1939');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('211','odelia_reeve@volutpat.com','Odelia Reeve','(98)61179-0212');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('212','deweyellwood@elit.com','Dewey Ellwood','(02)13205-6553');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('213','jessi.roberts@diam.com','Jessi Roberts','(98)29335-6573');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('214','pedrohoward@nec.com','Pedro Howard','(47)33015-1921');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('215','nellahood@odio.com','Nella Hood','(11)47888-4690');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('216','louiscrowther@pellentesque.com','Louis Crowther','(77)87211-5261');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('217','maggie.humphries@erat.com','Maggie Humphries','(45)53793-6112');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('218','meaghangarner@lectus.com','Meaghan Garner','(47)07326-9467');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('219','alexander.chester@pellentesque.com','Alexander Chester','(40)03982-5201');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('220','tranghowell@vel.com','Trang Howell','(55)78296-8620');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('221','laurence.metcalfe@vitae.com','Laurence Metcalfe','(88)33824-6288');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('222','cory_major@ut.com','Cory Major','(47)17010-9193');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('223','mandi.rodgers@senectus.com','Mandi Rodgers','(00)26362-4310');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('224','cristina_macdonald@aliquam.com','Cristina Macdonald','(90)15510-4154');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('225','holley.woodley@libero.com','Holley Woodley','(61)13970-7981');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('226','derick_pritchard@nunc.com','Derick Pritchard','(30)32801-5119');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('227','lesha_baxter@dictum.com','Lesha Baxter','(49)57796-7840');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('228','lizette_o_donnell@vulputate.com','Lizette O donnell','(83)15768-4453');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('229','adelinamccartney@arcu.com','Adelina Mccartney','(38)13944-2209');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('230','katherin.norman@risus.com','Katherin Norman','(47)68606-7299');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('231','gennabear@a.com','Genna Bear','(36)08404-0803');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('232','casandraspooner@magna.com','Casandra Spooner','(85)13726-3535');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('233','katherine.holloway@duis.com','Katherine Holloway','(82)46480-9627');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('234','mira.lynn@enim.com','Mira Lynn','(22)52016-7174');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('235','tarra_mohammed@sed.com','Tarra Mohammed','(94)85686-1577');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('236','yasuko.hartley@justo.com','Yasuko Hartley','(39)71854-0857');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('237','kylee_thomson@lectus.com','Kylee Thomson','(73)46152-3374');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('238','krysten_gale@purus.com','Krysten Gale','(42)71428-7956');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('239','mitchel.houghton@arcu.com','Mitchel Houghton','(07)09848-1072');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('240','evonne.halliday@imperdiet.com','Evonne Halliday','(31)61238-0925');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('241','stefani_silva@sit.com','Stefani Silva','(72)71215-8953');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('242','nelida.hutton@dictum.com','Nelida Hutton','(57)27565-7543');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('243','genesisconnor@vehicula.com','Genesis Connor','(55)87595-9768');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('244','tomoko.hutchinson@morbi.com','Tomoko Hutchinson','(91)84487-2535');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('245','casie_walsh@placerat.com','Casie Walsh','(05)76202-8750');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('246','marlinpatterson@velit.com','Marlin Patterson','(41)26849-2380');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('247','karlyhaworth@nunc.com','Karly Haworth','(66)78313-3229');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('248','ronnichamberlain@tincidunt.com','Ronni Chamberlain','(26)90330-0407');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('249','ilona_goddard@amet.com','Ilona Goddard','(90)02168-7045');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('250','shantay.copeland@bibendum.com','Shantay Copeland','(98)69347-3810');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('251','jona_brennan@turpis.com','Jona Brennan','(61)13596-7115');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('252','scott.meadows@vitae.com','Scott Meadows','(52)77360-3099');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('253','burmawheeler@ac.com','Burma Wheeler','(31)52403-3573');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('254','darcie.jenkins@duis.com','Darcie Jenkins','(22)62394-9288');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('255','samuel_martinez@elementum.com','Samuel Martinez','(94)30592-8191');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('256','carey.michael@pharetra.com','Carey Michael','(49)11375-4216');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('257','kanisha_rennie@ut.com','Kanisha Rennie','(78)14596-3140');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('258','eugenewhiteley@imperdiet.com','Eugene Whiteley','(20)33584-3103');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('259','lanell_downes@amet.com','Lanell Downes','(03)51209-8102');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('260','taishabanks@varius.com','Taisha Banks','(00)25789-4578');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('261','chaya.saunders@tellus.com','Chaya Saunders','(26)86315-7253');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('262','lou_scott@nulla.com','Lou Scott','(17)33591-9763');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('263','bryonlovell@scelerisque.com','Bryon Lovell','(28)87809-7274');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('264','berneicecope@sed.com','Berneice Cope','(95)89530-2579');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('265','leigh.robins@fermentum.com','Leigh Robins','(81)69705-2368');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('266','johnetta.john@eget.com','Johnetta John','(78)35814-3494');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('267','roman.stuart@convallis.com','Roman Stuart','(25)72646-3658');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('268','rufina.higgs@ac.com','Rufina Higgs','(92)98192-8623');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('269','sydneyriley@tellus.com','Sydney Riley','(56)90204-1384');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('270','freemanharper@ac.com','Freeman Harper','(84)53087-7911');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('271','tracey.clayton@eget.com','Tracey Clayton','(19)07653-0570');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('272','lynnewatson@lobortis.com','Lynne Watson','(20)37082-7851');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('273','nevadadurrant@habitant.com','Nevada Durrant','(61)00009-3058');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('274','venice.ashcroft@nisl.com','Venice Ashcroft','(66)74871-4089');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('275','clarita.edmonds@id.com','Clarita Edmonds','(58)21204-5163');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('276','maryln_ashton@arcu.com','Maryln Ashton','(03)26838-7597');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('277','reita.mclean@arcu.com','Reita Mclean','(35)33763-0749');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('278','alan.johnson@senectus.com','Alan Johnson','(58)09908-6388');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('279','lorenehamer@blandit.com','Lorene Hamer','(98)93744-5858');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('280','chrisgriffin@pharetra.com','Chris Griffin','(37)58574-4108');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('281','pansydale@auctor.com','Pansy Dale','(45)58485-4791');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('282','sha_craig@nunc.com','Sha Craig','(23)74117-2190');
Insert into COBRANCA.CLIENTE (CODIGO,EMAIL,NOME,TELEFONE) values ('283','shirlenegates@ornare.com','Shirlene Gates','(46)00082-6120');

commit;
